from arbolb import ArbolB

BT = ArbolB(2)
actual = BT.bTreeCreate()

print("Se insertara B")
# print(BT.raiz.llaves)
BT.bTreeInsert(actual, ord("B"))
print("Se insertara T")
BT.bTreeInsert(actual, ord("T"))
print("Se insertara H")
BT.bTreeInsert(actual, ord("H"))
# print("\n***Imprime raiz***")
# BT.imprimeNodo(BT.raiz)

print("Se insertara M")
BT.bTreeInsert(actual, ord("M"))
# print(BT.raiz.llaves)
# print(BT.raiz.hijos[1].llaves)
# print(BT.raiz.hijos[2].llaves)

print("Se insertara O")
BT.bTreeInsert(actual, ord("O"))
print("Se insertara C")
BT.bTreeInsert(actual, ord("C"))
# print(BT.raiz.llaves)
# print(BT.raiz.hijos[1].llaves)
# print(BT.raiz.hijos[2].llaves)

print("\nSe insertara Z")
BT.bTreeInsert(actual, ord("Z"))
# print(BT.raiz.llaves)
# print(BT.raiz.hijos[1].llaves)
# print(BT.raiz.hijos[2].llaves)
# print(BT.raiz.hijos[3].llaves)

# Insertar las llaves G,L,E,N,P,R,D,J,Q,F,W,X. 

print("Se insertara G")
BT.bTreeInsert(actual, ord("G"))
print("Se insertara L")
BT.bTreeInsert(actual, ord("L"))
print("Se insertara E")
BT.bTreeInsert(actual, ord("E"))
print("Se insertara N")
BT.bTreeInsert(actual, ord("N"))
print("Se insertara P")
BT.bTreeInsert(actual, ord("P"))
print("Se insertara R")
BT.bTreeInsert(actual, ord("R"))
print("Se insertara D")
BT.bTreeInsert(actual, ord("D"))
print("Se insertara J")
BT.bTreeInsert(actual, ord("J"))
print("Se insertara Q")
BT.bTreeInsert(actual, ord("Q"))
print("Se insertara F")
BT.bTreeInsert(actual, ord("F"))
print("Se insertara W")
BT.bTreeInsert(actual, ord("W"))
print("Se insertara X")
BT.bTreeInsert(actual, ord("X"))

print("\n*** Imprime Raiz ***")
BT.imprimeNodo(BT.raiz)
print("\nImpresion de las llaves")
print(BT.raiz.llaves)
print(BT.raiz.hijos[1].llaves)
print(BT.raiz.hijos[2].llaves)
print(BT.raiz.hijos[3].llaves)
